# Generated by Django 4.2.26 on 2025-11-28 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('port', models.IntegerField(help_text='Port number where service listens')),
                ('checker_script', models.CharField(help_text="Path to checker script (e.g., 'checkers.web_service_checker')", max_length=200)),
                ('checker_timeout', models.IntegerField(default=30, help_text='Checker timeout in seconds')),
                ('docker_image', models.CharField(help_text='Docker image name for this service', max_length=200)),
                ('container_name_template', models.CharField(default='{team_prefix}_{service_name}', help_text='Template for container naming', max_length=100)),
                ('supports_two_flags', models.BooleanField(default=True, help_text='Whether this service uses user + root flag system')),
                ('user_flag_points', models.IntegerField(default=50)),
                ('root_flag_points', models.IntegerField(default=150)),
                ('sla_points_per_tick', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('vpn_public_key', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_nop_team', models.BooleanField(default=False, help_text='NOP team used for testing exploits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_number', models.IntegerField(db_index=True, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=60, help_text='Expected duration in seconds')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=10)),
                ('flags_placed', models.IntegerField(default=0)),
                ('flags_checked', models.IntegerField(default=0)),
                ('checker_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticks',
                'ordering': ['-tick_number'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='gameserver.team')),
                ('attack_points', models.IntegerField(default=0)),
                ('defense_points', models.IntegerField(default=0)),
                ('sla_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('flags_captured', models.IntegerField(default=0)),
                ('flags_lost', models.IntegerField(default=0)),
                ('services_up', models.IntegerField(default=0)),
                ('services_total', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['-total_points', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('user', 'User Flag'), ('root', 'Root Flag')], default='user', max_length=4)),
                ('flag_value', models.CharField(db_index=True, max_length=128, unique=True)),
                ('flag_id', models.CharField(help_text='ID used by checker to retrieve flag', max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_stolen', models.BooleanField(default=False)),
                ('stolen_count', models.IntegerField(default=0, help_text='Number of teams that stole this flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='gameserver.service')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='gameserver.team')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='gameserver.tick')),
            ],
            options={
                'db_table': 'flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('corrupted', 'Corrupted'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('user_flag_placed', models.BooleanField(default=False)),
                ('root_flag_placed', models.BooleanField(default=False)),
                ('user_flag_retrieved', models.BooleanField(default=False)),
                ('root_flag_retrieved', models.BooleanField(default=False)),
                ('check_duration_ms', models.IntegerField(blank=True, help_text='Checker execution time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sla_percentage', models.FloatField(default=0.0, help_text='0-100 percentage for this check')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='gameserver.service')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='gameserver.team')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='gameserver.tick')),
            ],
            options={
                'db_table': 'service_statuses',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['team', 'service'], name='service_sta_team_id_74882e_idx'), models.Index(fields=['tick'], name='service_sta_tick_id_c0548b_idx'), models.Index(fields=['status'], name='service_sta_status_185f1f_idx')],
                'unique_together': {('team', 'service', 'tick')},
            },
        ),
        migrations.CreateModel(
            name='FlagSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(db_index=True, max_length=128)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('expired', 'Expired'), ('own_flag', 'Own Flag')], db_index=True, max_length=10)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='gameserver.flag')),
                ('submitter_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='gameserver.team')),
            ],
            options={
                'db_table': 'flag_submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['submitter_team', '-submitted_at'], name='flag_submis_submitt_b797eb_idx'), models.Index(fields=['flag'], name='flag_submis_flag_id_eb7fe9_idx'), models.Index(fields=['status'], name='flag_submis_status_ff7b86_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['flag_value'], name='flags_flag_va_2e673e_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['team', 'service', 'tick'], name='flags_team_id_ff126d_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['valid_until'], name='flags_valid_u_b2f4fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('team', 'service', 'tick', 'flag_type')},
        ),
    ]
