"""add_ssh_credentials_to_game_teams

Revision ID: 50a4450fc30f
Revises: b1c18323c759
Create Date: 2025-12-26 01:24:06.061836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a4450fc30f'
down_revision: Union[str, None] = 'b1c18323c759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_teams', sa.Column('ssh_username', sa.String(length=50), nullable=True))
    op.add_column('game_teams', sa.Column('ssh_password', sa.String(length=100), nullable=True))
    op.add_column('game_teams', sa.Column('ssh_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_teams', 'ssh_port')
    op.drop_column('game_teams', 'ssh_password')
    op.drop_column('game_teams', 'ssh_username')
    # ### end Alembic commands ###
