"""Add vulnboxes and checkers tables

Revision ID: 8e7dc35e9ea7
Revises: b1c18323c759
Create Date: 2025-12-31 00:27:44.577798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7dc35e9ea7'
down_revision: Union[str, None] = 'b1c18323c759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('vulnbox_id', sa.UUID(), nullable=True))
    op.add_column('games', sa.Column('checker_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'games', 'vulnboxes', ['vulnbox_id'], ['id'])
    op.create_foreign_key(None, 'games', 'checkers', ['checker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'checker_id')
    op.drop_column('games', 'vulnbox_id')
    # ### end Alembic commands ###
